package io.github.libfdx.backend.web;

import io.github.libfdx.runtime.core.shader.RuntimeShaderCompileRequest;
import io.github.libfdx.runtime.core.shader.RuntimeShaderCompileResult;
import io.github.libfdx.runtime.core.shader.RuntimeShaderCompileStage;
import io.github.libfdx.runtime.core.shader.RuntimeShaderCompileTarget;
import io.github.libfdx.runtime.core.shader.internal.NativeRuntimeShaderResultEnvelope;

/**
 * Generated immutable WebGL artifacts for the fixed shaders needed to render UI Kit during web startup.
 *
 * <p>WGSL remains canonical in its owning renderer. These exact-source-keyed artifacts were produced by the
 * compiler-enabled web runtime for WebGL GLSL ES 300. Regenerate them when
 * {@code WebBootstrapShaderArtifactsTest} reports canonical source drift.</p>
 */
final class WebBootstrapShaderArtifacts {
    private static final long FORWARD_OFFSET = 0xcbf29ce484222325L;
    private static final long REVERSE_OFFSET = 0x84222325cbf29ce4L;
    private static final long FNV_PRIME = 0x100000001b3L;

    private static final String SHAPE_VERTEX =
            "RkRYUgIAAAAAAAAAAQAAAAEDAAAAAAAAnwEAADAAAAAjdmVyc2lvbiAzMDAgZXMKCgpzdHJ1Y3QgVmVydGV4T3V0cHV0IHsKICB2" +
            "ZWM0IHBvc2l0aW9uOwogIHZlYzQgY29sb3I7Cn07CgpzdHJ1Y3QgVmVydGV4SW5wdXQgewogIHZlYzQgY2xpcFBvc2l0aW9uOwog" +
            "IHZlYzQgY29sb3I7Cn07CgpsYXlvdXQobG9jYXRpb24gPSAwKSBpbiB2ZWM0IHZlcnRleE1haW5fbG9jMF9JbnB1dDsKbGF5b3V0" +
            "KGxvY2F0aW9uID0gMSkgaW4gdmVjNCB2ZXJ0ZXhNYWluX2xvYzFfSW5wdXQ7CmxheW91dChsb2NhdGlvbiA9IDApIG91dCB2ZWM0" +
            "IHRpbnRfaW50ZXJzdGFnZV9sb2NhdGlvbjA7ClZlcnRleE91dHB1dCB2ZXJ0ZXhNYWluX2lubmVyKFZlcnRleElucHV0IHYpIHsK" +
            "ICBWZXJ0ZXhPdXRwdXQgdl8xID0gVmVydGV4T3V0cHV0KHZlYzQoMC4wZiksIHZlYzQoMC4wZikpOwogIHZfMS5wb3NpdGlvbiA9" +
            "IHYuY2xpcFBvc2l0aW9uOwogIHZfMS5jb2xvciA9IHYuY29sb3I7CiAgcmV0dXJuIHZfMTsKfQp2b2lkIG1haW4oKSB7CiAgVmVy" +
            "dGV4T3V0cHV0IHZfMiA9IHZlcnRleE1haW5faW5uZXIoVmVydGV4SW5wdXQodmVydGV4TWFpbl9sb2MwX0lucHV0LCB2ZXJ0ZXhN" +
            "YWluX2xvYzFfSW5wdXQpKTsKICBnbF9Qb3NpdGlvbiA9IHZlYzQodl8yLnBvc2l0aW9uLngsIC0odl8yLnBvc2l0aW9uLnkpLCAo" +
            "KDIuMGYgKiB2XzIucG9zaXRpb24ueikgLSB2XzIucG9zaXRpb24udyksIHZfMi5wb3NpdGlvbi53KTsKICB0aW50X2ludGVyc3Rh" +
            "Z2VfbG9jYXRpb24wID0gdl8yLmNvbG9yOwogIGdsX1BvaW50U2l6ZSA9IDEuMGY7Cn0KRkRYSQEAAAACAAAACgAAAHZlcnRleE1h" +
            "aW4BAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAA/////wIAAAASAAAAaW5wdXQuY2xpcFBvc2l0aW9uDAAAAGNsaXBQb3NpdGlv" +
            "bgAAAAD//////////wEAAAAEAAAAAQAAAAIAAAALAAAAaW5wdXQuY29sb3IFAAAAY29sb3IBAAAA//////////8BAAAABAAAAAEA" +
            "AAACAAAAAQAAAA4AAAA8cmV0dmFsPi5jb2xvcgUAAABjb2xvcgAAAAD//////////wEAAAAEAAAAAQAAAAIAAAAAAAAAAAAAAAwA" +
            "AABmcmFnbWVudE1haW4CAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAA/////wEAAAALAAAAaW5wdXQuY29sb3IFAAAAY29sb3IA" +
            "AAAA//////////8BAAAABAAAAAEAAAACAAAAAQAAAAgAAAA8cmV0dmFsPgAAAAAAAAAA//////////8BAAAABAAAAAEAAAACAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAEZEWFQBAAAAAQAAAAEAAAAKAAAAdmVydGV4TWFpbgoAAAB2ZXJ0ZXhNYWluAAAAAA==";

    private static final String SHAPE_FRAGMENT =
            "RkRYUgIAAAAAAAAAAQAAAJ0BAAAAAAAAnwEAADQAAAAjdmVyc2lvbiAzMDAgZXMKcHJlY2lzaW9uIGhpZ2hwIGZsb2F0OwpwcmVj" +
            "aXNpb24gaGlnaHAgaW50OwoKCnN0cnVjdCBWZXJ0ZXhPdXRwdXQgewogIHZlYzQgcG9zaXRpb247CiAgdmVjNCBjb2xvcjsKfTsK" +
            "CmxheW91dChsb2NhdGlvbiA9IDApIGluIHZlYzQgdGludF9pbnRlcnN0YWdlX2xvY2F0aW9uMDsKbGF5b3V0KGxvY2F0aW9uID0g" +
            "MCkgb3V0IHZlYzQgZnJhZ21lbnRNYWluX2xvYzBfT3V0cHV0Owp2ZWM0IGZyYWdtZW50TWFpbl9pbm5lcihWZXJ0ZXhPdXRwdXQg" +
            "dikgewogIHJldHVybiB2LmNvbG9yOwp9CnZvaWQgbWFpbigpIHsKICBmcmFnbWVudE1haW5fbG9jMF9PdXRwdXQgPSBmcmFnbWVu" +
            "dE1haW5faW5uZXIoVmVydGV4T3V0cHV0KGdsX0ZyYWdDb29yZCwgdGludF9pbnRlcnN0YWdlX2xvY2F0aW9uMCkpOwp9CkZEWEkB" +
            "AAAAAgAAAAoAAAB2ZXJ0ZXhNYWluAQAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAP////8CAAAAEgAAAGlucHV0LmNsaXBQb3Np" +
            "dGlvbgwAAABjbGlwUG9zaXRpb24AAAAA//////////8BAAAABAAAAAEAAAACAAAACwAAAGlucHV0LmNvbG9yBQAAAGNvbG9yAQAA" +
            "AP//////////AQAAAAQAAAABAAAAAgAAAAEAAAAOAAAAPHJldHZhbD4uY29sb3IFAAAAY29sb3IAAAAA//////////8BAAAABAAA" +
            "AAEAAAACAAAAAAAAAAAAAAAMAAAAZnJhZ21lbnRNYWluAgAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAP////8BAAAACwAAAGlu" +
            "cHV0LmNvbG9yBQAAAGNvbG9yAAAAAP//////////AQAAAAQAAAABAAAAAgAAAAEAAAAIAAAAPHJldHZhbD4AAAAAAAAAAP//////" +
            "////AQAAAAQAAAABAAAAAgAAAAAAAAAAAAAAAAAAAAAAAABGRFhUAQAAAAEAAAACAAAADAAAAGZyYWdtZW50TWFpbgwAAABmcmFn" +
            "bWVudE1haW4AAAAA";

    private static final String SPRITE_VERTEX =
            "RkRYUgIAAAAAAAAAAQAAAAYEAAAAAAAAEgMAADAAAAAjdmVyc2lvbiAzMDAgZXMKCgpzdHJ1Y3QgVmVydGV4T3V0cHV0IHsKICB2" +
            "ZWM0IHBvc2l0aW9uOwogIHZlYzIgdGV4Q29vcmQ7CiAgdmVjNCBjb2xvcjsKfTsKCnN0cnVjdCBWZXJ0ZXhJbnB1dCB7CiAgdmVj" +
            "MiBwb3NpdGlvbjsKICB2ZWMyIHRleENvb3JkOwogIHZlYzQgY29sb3I7Cn07CgpsYXlvdXQobG9jYXRpb24gPSAwKSBpbiB2ZWMy" +
            "IHZlcnRleE1haW5fbG9jMF9JbnB1dDsKbGF5b3V0KGxvY2F0aW9uID0gMSkgaW4gdmVjMiB2ZXJ0ZXhNYWluX2xvYzFfSW5wdXQ7" +
            "CmxheW91dChsb2NhdGlvbiA9IDIpIGluIHZlYzQgdmVydGV4TWFpbl9sb2MyX0lucHV0OwpsYXlvdXQobG9jYXRpb24gPSAwKSBv" +
            "dXQgdmVjMiB0aW50X2ludGVyc3RhZ2VfbG9jYXRpb24wOwpsYXlvdXQobG9jYXRpb24gPSAxKSBvdXQgdmVjNCB0aW50X2ludGVy" +
            "c3RhZ2VfbG9jYXRpb24xOwpWZXJ0ZXhPdXRwdXQgdmVydGV4TWFpbl9pbm5lcihWZXJ0ZXhJbnB1dCB2KSB7CiAgVmVydGV4T3V0" +
            "cHV0IHZfMSA9IFZlcnRleE91dHB1dCh2ZWM0KDAuMGYpLCB2ZWMyKDAuMGYpLCB2ZWM0KDAuMGYpKTsKICB2XzEucG9zaXRpb24g" +
            "PSB2ZWM0KHYucG9zaXRpb24sIDAuMGYsIDEuMGYpOwogIHZfMS50ZXhDb29yZCA9IHYudGV4Q29vcmQ7CiAgdl8xLmNvbG9yID0g" +
            "di5jb2xvcjsKICByZXR1cm4gdl8xOwp9CnZvaWQgbWFpbigpIHsKICBWZXJ0ZXhPdXRwdXQgdl8yID0gdmVydGV4TWFpbl9pbm5l" +
            "cihWZXJ0ZXhJbnB1dCh2ZXJ0ZXhNYWluX2xvYzBfSW5wdXQsIHZlcnRleE1haW5fbG9jMV9JbnB1dCwgdmVydGV4TWFpbl9sb2My" +
            "X0lucHV0KSk7CiAgZ2xfUG9zaXRpb24gPSB2ZWM0KHZfMi5wb3NpdGlvbi54LCAtKHZfMi5wb3NpdGlvbi55KSwgKCgyLjBmICog" +
            "dl8yLnBvc2l0aW9uLnopIC0gdl8yLnBvc2l0aW9uLncpLCB2XzIucG9zaXRpb24udyk7CiAgdGludF9pbnRlcnN0YWdlX2xvY2F0" +
            "aW9uMCA9IHZfMi50ZXhDb29yZDsKICB0aW50X2ludGVyc3RhZ2VfbG9jYXRpb24xID0gdl8yLmNvbG9yOwogIGdsX1BvaW50U2l6" +
            "ZSA9IDEuMGY7Cn0KRkRYSQEAAAACAAAACgAAAHZlcnRleE1haW4BAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAA/////wMAAAAO" +
            "AAAAaW5wdXQucG9zaXRpb24IAAAAcG9zaXRpb24AAAAA//////////8BAAAAAgAAAAEAAAACAAAADgAAAGlucHV0LnRleENvb3Jk" +
            "CAAAAHRleENvb3JkAQAAAP//////////AQAAAAIAAAABAAAAAgAAAAsAAABpbnB1dC5jb2xvcgUAAABjb2xvcgIAAAD/////////" +
            "/wEAAAAEAAAAAQAAAAIAAAACAAAAEQAAADxyZXR2YWw+LnRleENvb3JkCAAAAHRleENvb3JkAAAAAP//////////AQAAAAIAAAAB" +
            "AAAAAgAAAA4AAAA8cmV0dmFsPi5jb2xvcgUAAABjb2xvcgEAAAD//////////wEAAAAEAAAAAQAAAAIAAAAAAAAAAAAAAAwAAABm" +
            "cmFnbWVudE1haW4CAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAA/////wIAAAAOAAAAaW5wdXQudGV4Q29vcmQIAAAAdGV4Q29v" +
            "cmQAAAAA//////////8BAAAAAgAAAAEAAAACAAAACwAAAGlucHV0LmNvbG9yBQAAAGNvbG9yAQAAAP//////////AQAAAAQAAAAB" +
            "AAAAAgAAAAEAAAAIAAAAPHJldHZhbD4AAAAAAAAAAP//////////AQAAAAQAAAABAAAAAgAAAAAAAAACAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAABAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAJAAAAdV90ZXh0dXJlBAAAAAEAAAACAAAA/////wAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAIAAAAGAAAAAAAAAAAAAAD/////AAAAAAAAAAABAAAACQAAAHVfc2FtcGxlcgMAAAAAAAAAAgAAAP////8AAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAA/////wAAAAAAAAAARkRYVAEAAAABAAAAAQAAAAoAAAB2ZXJ0ZXhN" +
            "YWluCgAAAHZlcnRleE1haW4AAAAA";

    private static final String SPRITE_FRAGMENT =
            "RkRYUgIAAAAAAAAAAQAAAF8CAAAAAAAAEgMAAJoAAAAjdmVyc2lvbiAzMDAgZXMKcHJlY2lzaW9uIGhpZ2hwIGZsb2F0OwpwcmVj" +
            "aXNpb24gaGlnaHAgaW50OwoKCnN0cnVjdCBWZXJ0ZXhPdXRwdXQgewogIHZlYzQgcG9zaXRpb247CiAgdmVjMiB0ZXhDb29yZDsK" +
            "ICB2ZWM0IGNvbG9yOwp9OwoKdW5pZm9ybSBoaWdocCBzYW1wbGVyMkQgZl91X3RleHR1cmVfdV9zYW1wbGVyOwpsYXlvdXQobG9j" +
            "YXRpb24gPSAwKSBpbiB2ZWMyIHRpbnRfaW50ZXJzdGFnZV9sb2NhdGlvbjA7CmxheW91dChsb2NhdGlvbiA9IDEpIGluIHZlYzQg" +
            "dGludF9pbnRlcnN0YWdlX2xvY2F0aW9uMTsKbGF5b3V0KGxvY2F0aW9uID0gMCkgb3V0IHZlYzQgZnJhZ21lbnRNYWluX2xvYzBf" +
            "T3V0cHV0Owp2ZWM0IGZyYWdtZW50TWFpbl9pbm5lcihWZXJ0ZXhPdXRwdXQgdikgewogIHJldHVybiAodGV4dHVyZShmX3VfdGV4" +
            "dHVyZV91X3NhbXBsZXIsIHYudGV4Q29vcmQpICogdi5jb2xvcik7Cn0Kdm9pZCBtYWluKCkgewogIGZyYWdtZW50TWFpbl9sb2Mw" +
            "X091dHB1dCA9IGZyYWdtZW50TWFpbl9pbm5lcihWZXJ0ZXhPdXRwdXQoZ2xfRnJhZ0Nvb3JkLCB0aW50X2ludGVyc3RhZ2VfbG9j" +
            "YXRpb24wLCB0aW50X2ludGVyc3RhZ2VfbG9jYXRpb24xKSk7Cn0KRkRYSQEAAAACAAAACgAAAHZlcnRleE1haW4BAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAgAAAAAAAA/////wMAAAAOAAAAaW5wdXQucG9zaXRpb24IAAAAcG9zaXRpb24AAAAA//////////8BAAAAAgAA" +
            "AAEAAAACAAAADgAAAGlucHV0LnRleENvb3JkCAAAAHRleENvb3JkAQAAAP//////////AQAAAAIAAAABAAAAAgAAAAsAAABpbnB1" +
            "dC5jb2xvcgUAAABjb2xvcgIAAAD//////////wEAAAAEAAAAAQAAAAIAAAACAAAAEQAAADxyZXR2YWw+LnRleENvb3JkCAAAAHRl" +
            "eENvb3JkAAAAAP//////////AQAAAAIAAAABAAAAAgAAAA4AAAA8cmV0dmFsPi5jb2xvcgUAAABjb2xvcgEAAAD//////////wEA" +
            "AAAEAAAAAQAAAAIAAAAAAAAAAAAAAAwAAABmcmFnbWVudE1haW4CAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAA/////wIAAAAO" +
            "AAAAaW5wdXQudGV4Q29vcmQIAAAAdGV4Q29vcmQAAAAA//////////8BAAAAAgAAAAEAAAACAAAACwAAAGlucHV0LmNvbG9yBQAA" +
            "AGNvbG9yAQAAAP//////////AQAAAAQAAAABAAAAAgAAAAEAAAAIAAAAPHJldHZhbD4AAAAAAAAAAP//////////AQAAAAQAAAAB" +
            "AAAAAgAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAJAAAAdV90ZXh0dXJlBAAA" +
            "AAEAAAACAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAGAAAAAAAAAAAAAAD/////AAAAAAAAAAABAAAACQAAAHVf" +
            "c2FtcGxlcgMAAAAAAAAAAgAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAA/////wAAAAAAAAAA" +
            "RkRYVAEAAAABAAAAAgAAAAwAAABmcmFnbWVudE1haW4MAAAAZnJhZ21lbnRNYWluAgAAAAAAAAAAAAAAAAAAAAEAAAAHAAAAdGV4" +
            "dHVyZQAAAAAAAAAACAAAAHJlc291cmNlAAAAAAAAAAABAAAAAAAAAAEAAAAHAAAAc2FtcGxlcgAAAAABAAAACAAAAHJlc291cmNl" +
            "AAAAAA==";

    private static final String WHITE_SPRITE_VERTEX =
            "RkRYUgIAAAAAAAAAAQAAABoDAAAAAAAAcwIAADAAAAAjdmVyc2lvbiAzMDAgZXMKCgpzdHJ1Y3QgVmVydGV4T3V0cHV0IHsKICB2" +
            "ZWM0IHBvc2l0aW9uOwogIHZlYzIgdGV4Q29vcmQ7Cn07CgpzdHJ1Y3QgVmVydGV4SW5wdXQgewogIHZlYzIgcG9zaXRpb247CiAg" +
            "dmVjMiB0ZXhDb29yZDsKfTsKCmxheW91dChsb2NhdGlvbiA9IDApIGluIHZlYzIgdmVydGV4TWFpbl9sb2MwX0lucHV0OwpsYXlv" +
            "dXQobG9jYXRpb24gPSAxKSBpbiB2ZWMyIHZlcnRleE1haW5fbG9jMV9JbnB1dDsKbGF5b3V0KGxvY2F0aW9uID0gMCkgb3V0IHZl" +
            "YzIgdGludF9pbnRlcnN0YWdlX2xvY2F0aW9uMDsKVmVydGV4T3V0cHV0IHZlcnRleE1haW5faW5uZXIoVmVydGV4SW5wdXQgdikg" +
            "ewogIFZlcnRleE91dHB1dCB2XzEgPSBWZXJ0ZXhPdXRwdXQodmVjNCgwLjBmKSwgdmVjMigwLjBmKSk7CiAgdl8xLnBvc2l0aW9u" +
            "ID0gdmVjNCh2LnBvc2l0aW9uLCAwLjBmLCAxLjBmKTsKICB2XzEudGV4Q29vcmQgPSB2LnRleENvb3JkOwogIHJldHVybiB2XzE7" +
            "Cn0Kdm9pZCBtYWluKCkgewogIFZlcnRleE91dHB1dCB2XzIgPSB2ZXJ0ZXhNYWluX2lubmVyKFZlcnRleElucHV0KHZlcnRleE1h" +
            "aW5fbG9jMF9JbnB1dCwgdmVydGV4TWFpbl9sb2MxX0lucHV0KSk7CiAgZ2xfUG9zaXRpb24gPSB2ZWM0KHZfMi5wb3NpdGlvbi54" +
            "LCAtKHZfMi5wb3NpdGlvbi55KSwgKCgyLjBmICogdl8yLnBvc2l0aW9uLnopIC0gdl8yLnBvc2l0aW9uLncpLCB2XzIucG9zaXRp" +
            "b24udyk7CiAgdGludF9pbnRlcnN0YWdlX2xvY2F0aW9uMCA9IHZfMi50ZXhDb29yZDsKICBnbF9Qb2ludFNpemUgPSAxLjBmOwp9" +
            "CkZEWEkBAAAAAgAAAAoAAAB2ZXJ0ZXhNYWluAQAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAP////8CAAAADgAAAGlucHV0LnBv" +
            "c2l0aW9uCAAAAHBvc2l0aW9uAAAAAP//////////AQAAAAIAAAABAAAAAgAAAA4AAABpbnB1dC50ZXhDb29yZAgAAAB0ZXhDb29y" +
            "ZAEAAAD//////////wEAAAACAAAAAQAAAAIAAAABAAAAEQAAADxyZXR2YWw+LnRleENvb3JkCAAAAHRleENvb3JkAAAAAP//////" +
            "////AQAAAAIAAAABAAAAAgAAAAAAAAAAAAAADAAAAGZyYWdtZW50TWFpbgIAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAD/////" +
            "AQAAAA4AAABpbnB1dC50ZXhDb29yZAgAAAB0ZXhDb29yZAAAAAD//////////wEAAAACAAAAAQAAAAIAAAABAAAACAAAADxyZXR2" +
            "YWw+AAAAAAAAAAD//////////wEAAAAEAAAAAQAAAAIAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAA" +
            "AgAAAAAAAAAAAAAACQAAAHVfdGV4dHVyZQQAAAABAAAAAgAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAABgAAAAAA" +
            "AAAAAAAA/////wAAAAAAAAAAAQAAAAkAAAB1X3NhbXBsZXIDAAAAAAAAAAIAAAD/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAEAAAAAAAAAP////8AAAAAAAAAAEZEWFQBAAAAAQAAAAEAAAAKAAAAdmVydGV4TWFpbgoAAAB2ZXJ0ZXhNYWluAAAA" +
            "AA==";

    private static final String WHITE_SPRITE_FRAGMENT =
            "RkRYUgIAAAAAAAAAAQAAAPIBAAAAAAAAcwIAAJoAAAAjdmVyc2lvbiAzMDAgZXMKcHJlY2lzaW9uIGhpZ2hwIGZsb2F0OwpwcmVj" +
            "aXNpb24gaGlnaHAgaW50OwoKCnN0cnVjdCBWZXJ0ZXhPdXRwdXQgewogIHZlYzQgcG9zaXRpb247CiAgdmVjMiB0ZXhDb29yZDsK" +
            "fTsKCnVuaWZvcm0gaGlnaHAgc2FtcGxlcjJEIGZfdV90ZXh0dXJlX3Vfc2FtcGxlcjsKbGF5b3V0KGxvY2F0aW9uID0gMCkgaW4g" +
            "dmVjMiB0aW50X2ludGVyc3RhZ2VfbG9jYXRpb24wOwpsYXlvdXQobG9jYXRpb24gPSAwKSBvdXQgdmVjNCBmcmFnbWVudE1haW5f" +
            "bG9jMF9PdXRwdXQ7CnZlYzQgZnJhZ21lbnRNYWluX2lubmVyKFZlcnRleE91dHB1dCB2KSB7CiAgcmV0dXJuIHRleHR1cmUoZl91" +
            "X3RleHR1cmVfdV9zYW1wbGVyLCB2LnRleENvb3JkKTsKfQp2b2lkIG1haW4oKSB7CiAgZnJhZ21lbnRNYWluX2xvYzBfT3V0cHV0" +
            "ID0gZnJhZ21lbnRNYWluX2lubmVyKFZlcnRleE91dHB1dChnbF9GcmFnQ29vcmQsIHRpbnRfaW50ZXJzdGFnZV9sb2NhdGlvbjAp" +
            "KTsKfQpGRFhJAQAAAAIAAAAKAAAAdmVydGV4TWFpbgEAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAD/////AgAAAA4AAABpbnB1" +
            "dC5wb3NpdGlvbggAAABwb3NpdGlvbgAAAAD//////////wEAAAACAAAAAQAAAAIAAAAOAAAAaW5wdXQudGV4Q29vcmQIAAAAdGV4" +
            "Q29vcmQBAAAA//////////8BAAAAAgAAAAEAAAACAAAAAQAAABEAAAA8cmV0dmFsPi50ZXhDb29yZAgAAAB0ZXhDb29yZAAAAAD/" +
            "/////////wEAAAACAAAAAQAAAAIAAAAAAAAAAAAAAAwAAABmcmFnbWVudE1haW4CAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAA" +
            "/////wEAAAAOAAAAaW5wdXQudGV4Q29vcmQIAAAAdGV4Q29vcmQAAAAA//////////8BAAAAAgAAAAEAAAACAAAAAQAAAAgAAAA8" +
            "cmV0dmFsPgAAAAAAAAAA//////////8BAAAABAAAAAEAAAACAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAA" +
            "AAAAAAIAAAAAAAAAAAAAAAkAAAB1X3RleHR1cmUEAAAAAQAAAAIAAAD/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAYA" +
            "AAAAAAAAAAAAAP////8AAAAAAAAAAAEAAAAJAAAAdV9zYW1wbGVyAwAAAAAAAAACAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAABAAAAAAAAAD/////AAAAAAAAAABGRFhUAQAAAAEAAAACAAAADAAAAGZyYWdtZW50TWFpbgwAAABmcmFnbWVu" +
            "dE1haW4CAAAAAAAAAAAAAAAAAAAAAQAAAAcAAAB0ZXh0dXJlAAAAAAAAAAAIAAAAcmVzb3VyY2UAAAAAAAAAAAEAAAAAAAAAAQAA" +
            "AAcAAABzYW1wbGVyAAAAAAEAAAAIAAAAcmVzb3VyY2UAAAAA";

    private static final String INSTANCED_SPRITE_VERTEX =
            "RkRYUgIAAAAAAAAAAQAAAJoIAAAAAAAAdAMAADAAAAAjdmVyc2lvbiAzMDAgZXMKCgpzdHJ1Y3QgVmVydGV4T3V0cHV0IHsKICB2" +
            "ZWM0IHBvc2l0aW9uOwogIHZlYzIgdGV4Q29vcmQ7CiAgdmVjNCBjb2xvcjsKfTsKCnN0cnVjdCBWZXJ0ZXhJbnB1dCB7CiAgdmVj" +
            "NCBiYXNlQW5kRWRnZVg7CiAgdmVjNCBlZGdlWUFuZFV2QmFzZTsKICB2ZWM0IHV2U2l6ZUFuZENvbG9yUkc7CiAgdmVjMiBjb2xv" +
            "ckJBOwp9OwoKbGF5b3V0KGxvY2F0aW9uID0gMCkgaW4gdmVjNCB2ZXJ0ZXhNYWluX2xvYzBfSW5wdXQ7CmxheW91dChsb2NhdGlv" +
            "biA9IDEpIGluIHZlYzQgdmVydGV4TWFpbl9sb2MxX0lucHV0OwpsYXlvdXQobG9jYXRpb24gPSAyKSBpbiB2ZWM0IHZlcnRleE1h" +
            "aW5fbG9jMl9JbnB1dDsKbGF5b3V0KGxvY2F0aW9uID0gMykgaW4gdmVjMiB2ZXJ0ZXhNYWluX2xvYzNfSW5wdXQ7CmxheW91dChs" +
            "b2NhdGlvbiA9IDApIG91dCB2ZWMyIHRpbnRfaW50ZXJzdGFnZV9sb2NhdGlvbjA7CmxheW91dChsb2NhdGlvbiA9IDEpIG91dCB2" +
            "ZWM0IHRpbnRfaW50ZXJzdGFnZV9sb2NhdGlvbjE7ClZlcnRleE91dHB1dCB2ZXJ0ZXhNYWluX2lubmVyKHVpbnQgdmVydGV4SW5k" +
            "ZXgsIFZlcnRleElucHV0IHYpIHsKICBWZXJ0ZXhPdXRwdXQgdl8xID0gVmVydGV4T3V0cHV0KHZlYzQoMC4wZiksIHZlYzIoMC4w" +
            "ZiksIHZlYzQoMC4wZikpOwogIHVpbnQgY29ybmVySW5kZXggPSB2ZXJ0ZXhJbmRleDsKICBib29sIHZfMiA9IGZhbHNlOwogIGlm" +
            "ICgoY29ybmVySW5kZXggPT0gMnUpKSB7CiAgICB2XzIgPSB0cnVlOwogIH0gZWxzZSB7CiAgICB2XzIgPSAoY29ybmVySW5kZXgg" +
            "PT0gNHUpOwogIH0KICBib29sIHZfMyA9IGZhbHNlOwogIGlmICh2XzIpIHsKICAgIHZfMyA9IHRydWU7CiAgfSBlbHNlIHsKICAg" +
            "IHZfMyA9IChjb3JuZXJJbmRleCA9PSA1dSk7CiAgfQogIGJvb2wgdl80ID0gZmFsc2U7CiAgaWYgKChjb3JuZXJJbmRleCA9PSAx" +
            "dSkpIHsKICAgIHZfNCA9IHRydWU7CiAgfSBlbHNlIHsKICAgIHZfNCA9IChjb3JuZXJJbmRleCA9PSAydSk7CiAgfQogIGJvb2wg" +
            "dl81ID0gZmFsc2U7CiAgaWYgKHZfNCkgewogICAgdl81ID0gdHJ1ZTsKICB9IGVsc2UgewogICAgdl81ID0gKGNvcm5lckluZGV4" +
            "ID09IDR1KTsKICB9CiAgdmVjMiBjb3JuZXIgPSB2ZWMyKG1peCgwLjBmLCAxLjBmLCB2XzMpLCBtaXgoMC4wZiwgMS4wZiwgdl81" +
            "KSk7CiAgdmVjMiBiYXNlUG9zaXRpb24gPSB2ZWMyKHYuYmFzZUFuZEVkZ2VYLngsIHYuYmFzZUFuZEVkZ2VYLnkpOwogIHZlYzIg" +
            "ZWRnZVggPSB2ZWMyKHYuYmFzZUFuZEVkZ2VYLnosIHYuYmFzZUFuZEVkZ2VYLncpOwogIHZlYzIgZWRnZVkgPSB2ZWMyKHYuZWRn" +
            "ZVlBbmRVdkJhc2UueCwgdi5lZGdlWUFuZFV2QmFzZS55KTsKICB2ZWMyIHV2QmFzZSA9IHZlYzIodi5lZGdlWUFuZFV2QmFzZS56" +
            "LCB2LmVkZ2VZQW5kVXZCYXNlLncpOwogIHZlYzIgdXZTaXplID0gdmVjMih2LnV2U2l6ZUFuZENvbG9yUkcueCwgdi51dlNpemVB" +
            "bmRDb2xvclJHLnkpOwogIHZlYzQgY29sb3IgPSB2ZWM0KHYudXZTaXplQW5kQ29sb3JSRy56LCB2LnV2U2l6ZUFuZENvbG9yUkcu" +
            "dywgdi5jb2xvckJBLngsIHYuY29sb3JCQS55KTsKICB2ZWMyIHBvc2l0aW9uID0gKChiYXNlUG9zaXRpb24gKyAoZWRnZVggKiBj" +
            "b3JuZXIueCkpICsgKGVkZ2VZICogY29ybmVyLnkpKTsKICB2XzEucG9zaXRpb24gPSB2ZWM0KHBvc2l0aW9uLCAwLjBmLCAxLjBm" +
            "KTsKICB2XzEudGV4Q29vcmQgPSAodXZCYXNlICsgKHV2U2l6ZSAqIGNvcm5lcikpOwogIHZfMS5jb2xvciA9IGNvbG9yOwogIHJl" +
            "dHVybiB2XzE7Cn0Kdm9pZCBtYWluKCkgewogIHVpbnQgdl82ID0gdWludChnbF9WZXJ0ZXhJRCk7CiAgVmVydGV4T3V0cHV0IHZf" +
            "NyA9IHZlcnRleE1haW5faW5uZXIodl82LCBWZXJ0ZXhJbnB1dCh2ZXJ0ZXhNYWluX2xvYzBfSW5wdXQsIHZlcnRleE1haW5fbG9j" +
            "MV9JbnB1dCwgdmVydGV4TWFpbl9sb2MyX0lucHV0LCB2ZXJ0ZXhNYWluX2xvYzNfSW5wdXQpKTsKICBnbF9Qb3NpdGlvbiA9IHZl" +
            "YzQodl83LnBvc2l0aW9uLngsIC0odl83LnBvc2l0aW9uLnkpLCAoKDIuMGYgKiB2XzcucG9zaXRpb24ueikgLSB2XzcucG9zaXRp" +
            "b24udyksIHZfNy5wb3NpdGlvbi53KTsKICB0aW50X2ludGVyc3RhZ2VfbG9jYXRpb24wID0gdl83LnRleENvb3JkOwogIHRpbnRf" +
            "aW50ZXJzdGFnZV9sb2NhdGlvbjEgPSB2XzcuY29sb3I7CiAgZ2xfUG9pbnRTaXplID0gMS4wZjsKfQpGRFhJAQAAAAIAAAAKAAAA" +
            "dmVydGV4TWFpbgEAAAAAAAAAAAAAAAAAAAAAAAAAACAgAAAAAAD/////BAAAABIAAABpbnB1dC5iYXNlQW5kRWRnZVgMAAAAYmFz" +
            "ZUFuZEVkZ2VYAAAAAP//////////AQAAAAQAAAABAAAAAgAAABQAAABpbnB1dC5lZGdlWUFuZFV2QmFzZQ4AAABlZGdlWUFuZFV2" +
            "QmFzZQEAAAD//////////wEAAAAEAAAAAQAAAAIAAAAWAAAAaW5wdXQudXZTaXplQW5kQ29sb3JSRxAAAAB1dlNpemVBbmRDb2xv" +
            "clJHAgAAAP//////////AQAAAAQAAAABAAAAAgAAAA0AAABpbnB1dC5jb2xvckJBBwAAAGNvbG9yQkEDAAAA//////////8BAAAA" +
            "AgAAAAEAAAACAAAAAgAAABEAAAA8cmV0dmFsPi50ZXhDb29yZAgAAAB0ZXhDb29yZAAAAAD//////////wEAAAACAAAAAQAAAAIA" +
            "AAAOAAAAPHJldHZhbD4uY29sb3IFAAAAY29sb3IBAAAA//////////8BAAAABAAAAAEAAAACAAAAAAAAAAAAAAAMAAAAZnJhZ21l" +
            "bnRNYWluAgAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAP////8CAAAADgAAAGlucHV0LnRleENvb3JkCAAAAHRleENvb3JkAAAA" +
            "AP//////////AQAAAAIAAAABAAAAAgAAAAsAAABpbnB1dC5jb2xvcgUAAABjb2xvcgEAAAD//////////wEAAAAEAAAAAQAAAAIA" +
            "AAABAAAACAAAADxyZXR2YWw+AAAAAAAAAAD//////////wEAAAAEAAAAAQAAAAIAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAQAAAAAAAAAAAAAAAgAAAAAAAAAAAAAACQAAAHVfdGV4dHVyZQQAAAABAAAAAgAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAAAAACAAAABgAAAAAAAAAAAAAA/////wAAAAAAAAAAAQAAAAkAAAB1X3NhbXBsZXIDAAAAAAAAAAIAAAD/////AAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAP////8AAAAAAAAAAEZEWFQBAAAAAQAAAAEAAAAKAAAAdmVydGV4TWFpbgoA" +
            "AAB2ZXJ0ZXhNYWluAAAAAA==";

    private static final String INSTANCED_SPRITE_FRAGMENT =
            "RkRYUgIAAAAAAAAAAQAAAF8CAAAAAAAAdAMAAJoAAAAjdmVyc2lvbiAzMDAgZXMKcHJlY2lzaW9uIGhpZ2hwIGZsb2F0OwpwcmVj" +
            "aXNpb24gaGlnaHAgaW50OwoKCnN0cnVjdCBWZXJ0ZXhPdXRwdXQgewogIHZlYzQgcG9zaXRpb247CiAgdmVjMiB0ZXhDb29yZDsK" +
            "ICB2ZWM0IGNvbG9yOwp9OwoKdW5pZm9ybSBoaWdocCBzYW1wbGVyMkQgZl91X3RleHR1cmVfdV9zYW1wbGVyOwpsYXlvdXQobG9j" +
            "YXRpb24gPSAwKSBpbiB2ZWMyIHRpbnRfaW50ZXJzdGFnZV9sb2NhdGlvbjA7CmxheW91dChsb2NhdGlvbiA9IDEpIGluIHZlYzQg" +
            "dGludF9pbnRlcnN0YWdlX2xvY2F0aW9uMTsKbGF5b3V0KGxvY2F0aW9uID0gMCkgb3V0IHZlYzQgZnJhZ21lbnRNYWluX2xvYzBf" +
            "T3V0cHV0Owp2ZWM0IGZyYWdtZW50TWFpbl9pbm5lcihWZXJ0ZXhPdXRwdXQgdikgewogIHJldHVybiAodGV4dHVyZShmX3VfdGV4" +
            "dHVyZV91X3NhbXBsZXIsIHYudGV4Q29vcmQpICogdi5jb2xvcik7Cn0Kdm9pZCBtYWluKCkgewogIGZyYWdtZW50TWFpbl9sb2Mw" +
            "X091dHB1dCA9IGZyYWdtZW50TWFpbl9pbm5lcihWZXJ0ZXhPdXRwdXQoZ2xfRnJhZ0Nvb3JkLCB0aW50X2ludGVyc3RhZ2VfbG9j" +
            "YXRpb24wLCB0aW50X2ludGVyc3RhZ2VfbG9jYXRpb24xKSk7Cn0KRkRYSQEAAAACAAAACgAAAHZlcnRleE1haW4BAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAgIAAAAAAA/////wQAAAASAAAAaW5wdXQuYmFzZUFuZEVkZ2VYDAAAAGJhc2VBbmRFZGdlWAAAAAD/////////" +
            "/wEAAAAEAAAAAQAAAAIAAAAUAAAAaW5wdXQuZWRnZVlBbmRVdkJhc2UOAAAAZWRnZVlBbmRVdkJhc2UBAAAA//////////8BAAAA" +
            "BAAAAAEAAAACAAAAFgAAAGlucHV0LnV2U2l6ZUFuZENvbG9yUkcQAAAAdXZTaXplQW5kQ29sb3JSRwIAAAD//////////wEAAAAE" +
            "AAAAAQAAAAIAAAANAAAAaW5wdXQuY29sb3JCQQcAAABjb2xvckJBAwAAAP//////////AQAAAAIAAAABAAAAAgAAAAIAAAARAAAA" +
            "PHJldHZhbD4udGV4Q29vcmQIAAAAdGV4Q29vcmQAAAAA//////////8BAAAAAgAAAAEAAAACAAAADgAAADxyZXR2YWw+LmNvbG9y" +
            "BQAAAGNvbG9yAQAAAP//////////AQAAAAQAAAABAAAAAgAAAAAAAAAAAAAADAAAAGZyYWdtZW50TWFpbgIAAAAAAAAAAAAAAAAA" +
            "AAAAAAAAACAAAAAAAAD/////AgAAAA4AAABpbnB1dC50ZXhDb29yZAgAAAB0ZXhDb29yZAAAAAD//////////wEAAAACAAAAAQAA" +
            "AAIAAAALAAAAaW5wdXQuY29sb3IFAAAAY29sb3IBAAAA//////////8BAAAABAAAAAEAAAACAAAAAQAAAAgAAAA8cmV0dmFsPgAA" +
            "AAAAAAAA//////////8BAAAABAAAAAEAAAACAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAIAAAAA" +
            "AAAAAAAAAAkAAAB1X3RleHR1cmUEAAAAAQAAAAIAAAD/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAYAAAAAAAAAAAAA" +
            "AP////8AAAAAAAAAAAEAAAAJAAAAdV9zYW1wbGVyAwAAAAAAAAACAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
            "AAAABAAAAAAAAAD/////AAAAAAAAAABGRFhUAQAAAAEAAAACAAAADAAAAGZyYWdtZW50TWFpbgwAAABmcmFnbWVudE1haW4CAAAA" +
            "AAAAAAAAAAAAAAAAAQAAAAcAAAB0ZXh0dXJlAAAAAAAAAAAIAAAAcmVzb3VyY2UAAAAAAAAAAAEAAAAAAAAAAQAAAAcAAABzYW1w" +
            "bGVyAAAAAAEAAAAIAAAAcmVzb3VyY2UAAAAA";

    private static final String COMPACT_SPRITE_VERTEX =
            "RkRYUgIAAAAAAAAAAQAAAHcEAAAAAAAAUgMAADAAAAAjdmVyc2lvbiAzMDAgZXMKCgpzdHJ1Y3QgVmVydGV4T3V0cHV0IHsKICB2" +
            "ZWM0IHBvc2l0aW9uOwogIHZlYzIgdGV4Q29vcmQ7CiAgdmVjNCBjb2xvcjsKfTsKCnN0cnVjdCBWZXJ0ZXhJbnB1dCB7CiAgdmVj" +
            "MiBsb2NhbFBvc2l0aW9uOwogIHZlYzIgdGV4Q29vcmQ7CiAgdmVjNCBjb2xvcjsKICB2ZWMyIGNlbnRlcjsKfTsKCmxheW91dChs" +
            "b2NhdGlvbiA9IDApIGluIHZlYzIgdmVydGV4TWFpbl9sb2MwX0lucHV0OwpsYXlvdXQobG9jYXRpb24gPSAxKSBpbiB2ZWMyIHZl" +
            "cnRleE1haW5fbG9jMV9JbnB1dDsKbGF5b3V0KGxvY2F0aW9uID0gMikgaW4gdmVjNCB2ZXJ0ZXhNYWluX2xvYzJfSW5wdXQ7Cmxh" +
            "eW91dChsb2NhdGlvbiA9IDMpIGluIHZlYzIgdmVydGV4TWFpbl9sb2MzX0lucHV0OwpsYXlvdXQobG9jYXRpb24gPSAwKSBvdXQg" +
            "dmVjMiB0aW50X2ludGVyc3RhZ2VfbG9jYXRpb24wOwpsYXlvdXQobG9jYXRpb24gPSAxKSBvdXQgdmVjNCB0aW50X2ludGVyc3Rh" +
            "Z2VfbG9jYXRpb24xOwpWZXJ0ZXhPdXRwdXQgdmVydGV4TWFpbl9pbm5lcihWZXJ0ZXhJbnB1dCB2KSB7CiAgVmVydGV4T3V0cHV0" +
            "IHZfMSA9IFZlcnRleE91dHB1dCh2ZWM0KDAuMGYpLCB2ZWMyKDAuMGYpLCB2ZWM0KDAuMGYpKTsKICB2XzEucG9zaXRpb24gPSB2" +
            "ZWM0KCh2LmNlbnRlciArIHYubG9jYWxQb3NpdGlvbiksIDAuMGYsIDEuMGYpOwogIHZfMS50ZXhDb29yZCA9IHYudGV4Q29vcmQ7" +
            "CiAgdl8xLmNvbG9yID0gdi5jb2xvcjsKICByZXR1cm4gdl8xOwp9CnZvaWQgbWFpbigpIHsKICBWZXJ0ZXhPdXRwdXQgdl8yID0g" +
            "dmVydGV4TWFpbl9pbm5lcihWZXJ0ZXhJbnB1dCh2ZXJ0ZXhNYWluX2xvYzBfSW5wdXQsIHZlcnRleE1haW5fbG9jMV9JbnB1dCwg" +
            "dmVydGV4TWFpbl9sb2MyX0lucHV0LCB2ZXJ0ZXhNYWluX2xvYzNfSW5wdXQpKTsKICBnbF9Qb3NpdGlvbiA9IHZlYzQodl8yLnBv" +
            "c2l0aW9uLngsIC0odl8yLnBvc2l0aW9uLnkpLCAoKDIuMGYgKiB2XzIucG9zaXRpb24ueikgLSB2XzIucG9zaXRpb24udyksIHZf" +
            "Mi5wb3NpdGlvbi53KTsKICB0aW50X2ludGVyc3RhZ2VfbG9jYXRpb24wID0gdl8yLnRleENvb3JkOwogIHRpbnRfaW50ZXJzdGFn" +
            "ZV9sb2NhdGlvbjEgPSB2XzIuY29sb3I7CiAgZ2xfUG9pbnRTaXplID0gMS4wZjsKfQpGRFhJAQAAAAIAAAAKAAAAdmVydGV4TWFp" +
            "bgEAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAD/////BAAAABMAAABpbnB1dC5sb2NhbFBvc2l0aW9uDQAAAGxvY2FsUG9zaXRp" +
            "b24AAAAA//////////8BAAAAAgAAAAEAAAACAAAADgAAAGlucHV0LnRleENvb3JkCAAAAHRleENvb3JkAQAAAP//////////AQAA" +
            "AAIAAAABAAAAAgAAAAsAAABpbnB1dC5jb2xvcgUAAABjb2xvcgIAAAD//////////wEAAAAEAAAAAQAAAAIAAAAMAAAAaW5wdXQu" +
            "Y2VudGVyBgAAAGNlbnRlcgMAAAD//////////wEAAAACAAAAAQAAAAIAAAACAAAAEQAAADxyZXR2YWw+LnRleENvb3JkCAAAAHRl" +
            "eENvb3JkAAAAAP//////////AQAAAAIAAAABAAAAAgAAAA4AAAA8cmV0dmFsPi5jb2xvcgUAAABjb2xvcgEAAAD//////////wEA" +
            "AAAEAAAAAQAAAAIAAAAAAAAAAAAAAAwAAABmcmFnbWVudE1haW4CAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAA/////wIAAAAO" +
            "AAAAaW5wdXQudGV4Q29vcmQIAAAAdGV4Q29vcmQAAAAA//////////8BAAAAAgAAAAEAAAACAAAACwAAAGlucHV0LmNvbG9yBQAA" +
            "AGNvbG9yAQAAAP//////////AQAAAAQAAAABAAAAAgAAAAEAAAAIAAAAPHJldHZhbD4AAAAAAAAAAP//////////AQAAAAQAAAAB" +
            "AAAAAgAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAJAAAAdV90ZXh0dXJlBAAA" +
            "AAEAAAACAAAA/////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAGAAAAAAAAAAAAAAD/////AAAAAAAAAAABAAAACQAAAHVf" +
            "c2FtcGxlcgMAAAAAAAAAAgAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAA/////wAAAAAAAAAA" +
            "RkRYVAEAAAABAAAAAQAAAAoAAAB2ZXJ0ZXhNYWluCgAAAHZlcnRleE1haW4AAAAA";

    private static final String COMPACT_SPRITE_FRAGMENT =
            "RkRYUgIAAAAAAAAAAQAAAF8CAAAAAAAAUgMAAJoAAAAjdmVyc2lvbiAzMDAgZXMKcHJlY2lzaW9uIGhpZ2hwIGZsb2F0OwpwcmVj" +
            "aXNpb24gaGlnaHAgaW50OwoKCnN0cnVjdCBWZXJ0ZXhPdXRwdXQgewogIHZlYzQgcG9zaXRpb247CiAgdmVjMiB0ZXhDb29yZDsK" +
            "ICB2ZWM0IGNvbG9yOwp9OwoKdW5pZm9ybSBoaWdocCBzYW1wbGVyMkQgZl91X3RleHR1cmVfdV9zYW1wbGVyOwpsYXlvdXQobG9j" +
            "YXRpb24gPSAwKSBpbiB2ZWMyIHRpbnRfaW50ZXJzdGFnZV9sb2NhdGlvbjA7CmxheW91dChsb2NhdGlvbiA9IDEpIGluIHZlYzQg" +
            "dGludF9pbnRlcnN0YWdlX2xvY2F0aW9uMTsKbGF5b3V0KGxvY2F0aW9uID0gMCkgb3V0IHZlYzQgZnJhZ21lbnRNYWluX2xvYzBf" +
            "T3V0cHV0Owp2ZWM0IGZyYWdtZW50TWFpbl9pbm5lcihWZXJ0ZXhPdXRwdXQgdikgewogIHJldHVybiAodGV4dHVyZShmX3VfdGV4" +
            "dHVyZV91X3NhbXBsZXIsIHYudGV4Q29vcmQpICogdi5jb2xvcik7Cn0Kdm9pZCBtYWluKCkgewogIGZyYWdtZW50TWFpbl9sb2Mw" +
            "X091dHB1dCA9IGZyYWdtZW50TWFpbl9pbm5lcihWZXJ0ZXhPdXRwdXQoZ2xfRnJhZ0Nvb3JkLCB0aW50X2ludGVyc3RhZ2VfbG9j" +
            "YXRpb24wLCB0aW50X2ludGVyc3RhZ2VfbG9jYXRpb24xKSk7Cn0KRkRYSQEAAAACAAAACgAAAHZlcnRleE1haW4BAAAAAAAAAAAA" +
            "AAAAAAAAAAAAAAAgAAAAAAAA/////wQAAAATAAAAaW5wdXQubG9jYWxQb3NpdGlvbg0AAABsb2NhbFBvc2l0aW9uAAAAAP//////" +
            "////AQAAAAIAAAABAAAAAgAAAA4AAABpbnB1dC50ZXhDb29yZAgAAAB0ZXhDb29yZAEAAAD//////////wEAAAACAAAAAQAAAAIA" +
            "AAALAAAAaW5wdXQuY29sb3IFAAAAY29sb3ICAAAA//////////8BAAAABAAAAAEAAAACAAAADAAAAGlucHV0LmNlbnRlcgYAAABj" +
            "ZW50ZXIDAAAA//////////8BAAAAAgAAAAEAAAACAAAAAgAAABEAAAA8cmV0dmFsPi50ZXhDb29yZAgAAAB0ZXhDb29yZAAAAAD/" +
            "/////////wEAAAACAAAAAQAAAAIAAAAOAAAAPHJldHZhbD4uY29sb3IFAAAAY29sb3IBAAAA//////////8BAAAABAAAAAEAAAAC" +
            "AAAAAAAAAAAAAAAMAAAAZnJhZ21lbnRNYWluAgAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAP////8CAAAADgAAAGlucHV0LnRl" +
            "eENvb3JkCAAAAHRleENvb3JkAAAAAP//////////AQAAAAIAAAABAAAAAgAAAAsAAABpbnB1dC5jb2xvcgUAAABjb2xvcgEAAAD/" +
            "/////////wEAAAAEAAAAAQAAAAIAAAABAAAACAAAADxyZXR2YWw+AAAAAAAAAAD//////////wEAAAAEAAAAAQAAAAIAAAAAAAAA" +
            "AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAgAAAAAAAAAAAAAACQAAAHVfdGV4dHVyZQQAAAABAAAAAgAAAP//" +
            "//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAABgAAAAAAAAAAAAAA/////wAAAAAAAAAAAQAAAAkAAAB1X3NhbXBsZXIDAAAA" +
            "AAAAAAIAAAD/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAP////8AAAAAAAAAAEZEWFQBAAAAAQAA" +
            "AAIAAAAMAAAAZnJhZ21lbnRNYWluDAAAAGZyYWdtZW50TWFpbgIAAAAAAAAAAAAAAAAAAAABAAAABwAAAHRleHR1cmUAAAAAAAAA" +
            "AAgAAAByZXNvdXJjZQAAAAAAAAAAAQAAAAAAAAABAAAABwAAAHNhbXBsZXIAAAAAAQAAAAgAAAByZXNvdXJjZQAAAAA=";

    private static final Entry[] ENTRIES = {
            new Entry(494, 0xc7d493ee9719745dL, 0xa0ca8f4479258464L,
                    SHAPE_VERTEX, SHAPE_FRAGMENT),
            new Entry(751, 0x9ed238b486d35290L, 0x1d0786ea914b03b3L,
                    SPRITE_VERTEX, SPRITE_FRAGMENT),
            new Entry(641, 0x78ccf8ea42612441L, 0xeb677dceeebb711aL,
                    WHITE_SPRITE_VERTEX, WHITE_SPRITE_FRAGMENT),
            new Entry(1628, 0x8e8218623f03c909L, 0x6702fd5ea9ccb308L,
                    INSTANCED_SPRITE_VERTEX, INSTANCED_SPRITE_FRAGMENT),
            new Entry(809, 0x3187698b5508d930L, 0x37201d5e793bd58bL,
                    COMPACT_SPRITE_VERTEX, COMPACT_SPRITE_FRAGMENT)
    };

    private WebBootstrapShaderArtifacts() {
    }

    static RuntimeShaderCompileResult compile(RuntimeShaderCompileRequest request) {
        if (request == null || request.target() != RuntimeShaderCompileTarget.WEBGL_GLSL_ES
                || !"300".equals(request.glslEsProfile())) {
            return null;
        }
        RuntimeShaderCompileStage stage = request.stage();
        if ((stage != RuntimeShaderCompileStage.VERTEX
                && stage != RuntimeShaderCompileStage.FRAGMENT)
                || !(stage == RuntimeShaderCompileStage.VERTEX
                        ? "vertexMain" : "fragmentMain").equals(request.entryPoint())) {
            return null;
        }
        Entry entry = find(request.source());
        if (entry == null) {
            return null;
        }
        String encoded = stage == RuntimeShaderCompileStage.VERTEX
                ? entry.vertex : entry.fragment;
        return NativeRuntimeShaderResultEnvelope.decodeBase64(encoded);
    }

    static boolean contains(String source) {
        return find(source) != null;
    }

    private static Entry find(String source) {
        if (source == null) {
            return null;
        }
        long forward = FORWARD_OFFSET;
        for (int i = 0; i < source.length(); i++) {
            forward ^= source.charAt(i);
            forward *= FNV_PRIME;
        }
        long reverse = REVERSE_OFFSET;
        for (int i = source.length() - 1; i >= 0; i--) {
            reverse ^= source.charAt(i);
            reverse *= FNV_PRIME;
        }
        for (Entry entry : ENTRIES) {
            if (entry.length == source.length()
                    && entry.forward == forward
                    && entry.reverse == reverse) {
                return entry;
            }
        }
        return null;
    }

    private static final class Entry {
        final int length;
        final long forward;
        final long reverse;
        final String vertex;
        final String fragment;

        Entry(int length, long forward, long reverse,
                String vertex, String fragment) {
            this.length = length;
            this.forward = forward;
            this.reverse = reverse;
            this.vertex = vertex;
            this.fragment = fragment;
        }
    }
}
