import org.gradle.api.GradleException
import org.gradle.api.tasks.Copy
import org.gradle.language.jvm.tasks.ProcessResources

plugins {
    id("maven-publish")
    id("java-library")
}


java {
    sourceCompatibility = JavaVersion.toVersion(25)
    targetCompatibility = JavaVersion.toVersion(25)
}

val moduleName = "fdx_web"

base {
    archivesName.set(moduleName)
}

val fdxBuildProject = project(":libfdx:framework:fdx:fdx-build")
val runtimeFdxWebGeneratedResources = layout.buildDirectory.dir("generated/resources/runtimeFdxWeb")
val runtimeFdxBuildWebGeneratedResources =
    fdxBuildProject.layout.buildDirectory.dir("generated/resources/runtimeFdxWeb")

fun deleteUnexpectedWebRuntimeArtifacts(directory: File) {
    if (!directory.isDirectory) {
        return
    }
    val expected = setOf("fdx.js", "fdx.wasm")
    directory.listFiles()?.forEach { file ->
        if (file.isFile && file.name !in expected
            && (file.extension.equals("js", ignoreCase = true)
                || file.extension.equals("wasm", ignoreCase = true))
        ) {
            file.delete()
        }
    }
}

sourceSets {
    named("main") {
        resources.srcDir(runtimeFdxWebGeneratedResources)
    }
}

val generateRuntimeFdxWebNative = tasks.register<Copy>("generate_runtime_fdx_web_native") {
    group = "libfdx native"
    description = "Packages fdx.js and fdx.wasm generated by fdx-build into fdx_web resources."
    dependsOn(":libfdx:framework:fdx:fdx-build:build_runtime_fdx_web_native")
    from(runtimeFdxBuildWebGeneratedResources.map { it.file("fdx.js") })
    from(runtimeFdxBuildWebGeneratedResources.map { it.file("fdx.wasm") })
    into(runtimeFdxWebGeneratedResources)
    doFirst {
        deleteUnexpectedWebRuntimeArtifacts(runtimeFdxWebGeneratedResources.get().asFile)
    }
}

tasks.register("generate_runtime_fdx_web_native_prebuilt") {
    group = "libfdx native"
    description = "Packages runtime fdx web resources generated by fdx-build using fdx-natives prebuilt dependencies."
    dependsOn(generateRuntimeFdxWebNative)
}

tasks.named<ProcessResources>("processResources") {
    mustRunAfter(generateRuntimeFdxWebNative)
    doFirst {
        deleteUnexpectedWebRuntimeArtifacts(destinationDir)
    }
}

tasks.register("validate_runtime_fdx_web_native_resources") {
    group = "libfdx native"
    description = "Validates generated fdx_web native resources before packaging."
    doLast {
        val missing = listOf("fdx.js", "fdx.wasm")
            .map { runtimeFdxWebGeneratedResources.get().asFile.resolve(it) }
            .filterNot(File::isFile)
        if (missing.isNotEmpty()) {
            throw GradleException(
                "Missing generated fdx_web native resources:\n" +
                    missing.joinToString(separator = "\n") { " - ${it.absolutePath}" } + "\n" +
                    "Run :libfdx:framework:fdx:platform:web:generate_runtime_fdx_web_native first."
            )
        }
    }
}
java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            artifactId = moduleName
            from(components["java"])
        }
    }
}
