import org.gradle.api.GradleException
import org.gradle.api.tasks.Copy
import org.gradle.language.jvm.tasks.ProcessResources

plugins {
    id("maven-publish")
    id("java-library")
}


java {
    sourceCompatibility = JavaVersion.toVersion(25)
    targetCompatibility = JavaVersion.toVersion(25)
}

val moduleName = "fdx_desktop"

base {
    archivesName.set(moduleName)
}

val fdxBuildProject = project(":libfdx:framework:fdx:fdx-build")
val runtimeFdxDesktopGeneratedResources = layout.buildDirectory.dir("generated/resources/runtimeFdxDesktop")
val runtimeFdxBuildDesktopGeneratedResources =
    fdxBuildProject.layout.buildDirectory.dir("generated/resources/runtimeFdxDesktop")

val generatedDesktopRuntimeFdxNatives = mapOf(
    "windows-x64" to "fdx.dll",
    "linux-x64" to "libfdx.so",
    "macos-x64" to "libfdx.dylib",
    "macos-arm64" to "libfdx.dylib"
)

val requireAllRuntimeFdxNatives = providers.gradleProperty("libfdx.runtimeFdx.requireAllNativeResources")
    .map(String::toBoolean)
    .orElse(false)

fun runtimeFdxHostDesktopClassifier(): String? {
    val os = System.getProperty("os.name", "").lowercase()
    val arch = System.getProperty("os.arch", "").lowercase()
    val archPart = if (arch.contains("aarch64") || arch.contains("arm64")) {
        "arm64"
    } else {
        "x64"
    }
    return when {
        os.contains("windows") -> "windows-x64"
        os.contains("linux") && archPart == "x64" -> "linux-x64"
        os.contains("mac") || os.contains("darwin") -> "macos-$archPart"
        else -> null
    }
}

fun macosClassifier(): String {
    val arch = System.getProperty("os.arch").lowercase()
    return if (arch.contains("aarch64") || arch.contains("arm64")) {
        "macos-arm64"
    } else {
        "macos-x64"
    }
}

fun runtimeFdxBuildDesktopNative(classifier: String, fileName: String) =
    runtimeFdxBuildDesktopGeneratedResources.map { it.file("libfdx-native/desktop/$classifier/$fileName") }

fun runtimeFdxDesktopNativeOutput(classifier: String) =
    runtimeFdxDesktopGeneratedResources.map { it.dir("libfdx-native/desktop/$classifier") }

val generateRuntimeFdxWindowsNative = tasks.register<Copy>("generate_runtime_fdx_windows_native") {
    group = "libfdx native"
    description = "Packages fdx.dll generated by fdx-build into fdx_desktop resources."
    dependsOn(":libfdx:framework:fdx:fdx-build:build_runtime_fdx_windows_native")
    from(runtimeFdxBuildDesktopNative("windows-x64", "fdx.dll"))
    into(runtimeFdxDesktopNativeOutput("windows-x64"))
}

tasks.register("generate_runtime_fdx_windows_native_prebuilt") {
    group = "libfdx native"
    description = "Packages fdx.dll generated by fdx-build using fdx-natives prebuilt dependencies."
    dependsOn(generateRuntimeFdxWindowsNative)
}

val generateRuntimeFdxLinuxNative = tasks.register<Copy>("generate_runtime_fdx_linux_native") {
    group = "libfdx native"
    description = "Packages libfdx.so generated by fdx-build into fdx_desktop resources."
    dependsOn(":libfdx:framework:fdx:fdx-build:build_runtime_fdx_linux_native")
    from(runtimeFdxBuildDesktopNative("linux-x64", "libfdx.so"))
    into(runtimeFdxDesktopNativeOutput("linux-x64"))
}

tasks.register("generate_runtime_fdx_linux_native_prebuilt") {
    group = "libfdx native"
    description = "Packages libfdx.so generated by fdx-build using fdx-natives prebuilt dependencies."
    dependsOn(generateRuntimeFdxLinuxNative)
}

val generateRuntimeFdxMacosNative = tasks.register<Copy>("generate_runtime_fdx_macos_native") {
    group = "libfdx native"
    description = "Packages libfdx.dylib generated by fdx-build into fdx_desktop resources."
    val classifier = macosClassifier()
    dependsOn(":libfdx:framework:fdx:fdx-build:build_runtime_fdx_macos_native")
    from(runtimeFdxBuildDesktopNative(classifier, "libfdx.dylib"))
    into(runtimeFdxDesktopNativeOutput(classifier))
}

val generateRuntimeFdxHostNative = tasks.register("generate_runtime_fdx_host_native") {
    group = "libfdx native"
    description = "Packages the runtime fdx native for the current desktop host."
    when (runtimeFdxHostDesktopClassifier()) {
        "windows-x64" -> dependsOn(generateRuntimeFdxWindowsNative)
        "linux-x64" -> dependsOn(generateRuntimeFdxLinuxNative)
        "macos-x64", "macos-arm64" -> dependsOn(generateRuntimeFdxMacosNative)
        else -> doFirst {
            throw GradleException("Runtime fdx does not support this desktop host")
        }
    }
}

tasks.register("generate_runtime_fdx_macos_native_prebuilt") {
    group = "libfdx native"
    description = "Packages libfdx.dylib generated by fdx-build using fdx-natives prebuilt dependencies."
    dependsOn(generateRuntimeFdxMacosNative)
}

sourceSets {
    named("main") {
        resources.srcDir(runtimeFdxDesktopGeneratedResources)
    }
}

tasks.named<ProcessResources>("processResources") {
    dependsOn(generateRuntimeFdxHostNative)
    mustRunAfter(generateRuntimeFdxWindowsNative, generateRuntimeFdxLinuxNative, generateRuntimeFdxMacosNative)
}

tasks.register("validate_runtime_fdx_desktop_c_resources") {
    group = "libfdx native"
    description = "Validates generated fdx_desktop C resources before packaging."
    doLast {
        val desktopRoot = runtimeFdxDesktopGeneratedResources.get().asFile
        val missingRequiredFiles = mutableListOf<File>()
        val missingWarnedFiles = mutableListOf<File>()
        val requireAll = requireAllRuntimeFdxNatives.get()
        val hostDesktopClassifier = runtimeFdxHostDesktopClassifier()
        generatedDesktopRuntimeFdxNatives.forEach { (classifier, fileName) ->
            val file = desktopRoot.resolve("libfdx-native/desktop/$classifier/$fileName")
            if (!file.isFile) {
                if (requireAll || classifier == hostDesktopClassifier) {
                    missingRequiredFiles += file
                } else {
                    missingWarnedFiles += file
                }
            }
        }
        if (missingWarnedFiles.isNotEmpty()) {
            logger.warn(
                "Missing non-host fdx_desktop C resources; continuing because " +
                    "libfdx.runtimeFdx.requireAllNativeResources=false:\n" +
                    missingWarnedFiles.joinToString(separator = "\n") { " - ${it.absolutePath}" }
            )
        }
        if (missingRequiredFiles.isNotEmpty()) {
            throw GradleException(
                "Missing generated fdx_desktop C resources:\n" +
                    missingRequiredFiles.joinToString(separator = "\n") { " - ${it.absolutePath}" }
            )
        }
    }
}
java {
    withSourcesJar()
    withJavadocJar()
}

tasks.named("sourcesJar") {
    dependsOn(generateRuntimeFdxHostNative)
    mustRunAfter(generateRuntimeFdxWindowsNative, generateRuntimeFdxLinuxNative, generateRuntimeFdxMacosNative)
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            artifactId = moduleName
            from(components["java"])
        }
    }
}
